services:
  mysql:
    image: mysql:8.4
    container_name: educa-ar-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: My@@2026banco
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: educa_ar

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot123"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data: